version: '3'

services:
  test_service:
    build: ./test-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./test-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
    depends_on:
      - db
      
  categories_service:
    build: ./categories-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./categories-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
      - SERVICE_USER=admin
      - PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test_service
      - categories_service

