version: '3'

services:
  test_service:
    build: ./test-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./test-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
      - LOGIN=admin
      - PASSWORD=password
    depends_on:
      - db

  categories_service:
    build: ./categories-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./categories-service/:/app/
    ports:
      - 8002:8000
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth/basic
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
    depends_on:
      - auth_service
      - db

  auth_service:
    build: ./auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    ports:
      - 8003:8000
    environment:
      - LOGIN=admin
      - PASSWORD=password
    depends_on:
      - db

  products_service:
    build: ./products-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./products-service/:/app/
    ports:
      - 8004:8000
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth/basic
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
    depends_on:
      - auth_service
      - db

  orders_service:
    build: ./orders-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./orders-service/:/app/
    ports:
      - 8005:8000
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth/basic
      - DATABASE_URI=postgresql://northwind_user:thewindisblowing@db/northwind
    depends_on:
      - auth_service
      - products_service
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/google-containers/cadvisor
    container_name: cadvisor
    ports:
    - 9003:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - test_service
      - categories_service
      - products_service

volumes:
  prometheus_data: