global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090
