global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
        - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          - node_exporter:9100
  - job_name: categories-metrics
    metrics_path: /api/categories/metrics
    static_configs:
      - targets:
          - categories:8000
  - job_name: orders-metrics
    metrics_path: /api/orders/metrics
    static_configs:
      - targets:
          - orders:8000
  - job_name: products-metrics
    metrics_path: /api/products/metrics
    static_configs:
      - targets:
          - products:8000
